# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
options:
  create_default_artifact_root_if_missing:
    description: |
      If True, charm will try to create the default_artifact_root bucket in S3 if it does not 
      exist.  If False and the bucket does not exist, the charm enter Blocked status
    type: boolean
    default: true
  default_artifact_root:
    description: |
      The name of the default bucket mlflow uses for artifacts, if not specified by the workflow
    type: string
    default: mlflow
  mlflow_port:
    description: |
      The port MLFlow will be listening on
    type: int
    default: 5000
  mlflow_nodeport:
    description: |
      The nodeport for MLFlow
    type: int
    default: 31380
  mlflow_prometheus_exporter_port:
    description: |
      The port MLFlow Prometheus exporter will be listening on
    type: int
    default: 8000
  mlflow_prometheus_exporter_nodeport:
    description: |
      The nodeport for MLFlow Prometheus exporter
    type: int
    default: 31381
  enable_mlflow_nodeport:
    description: Deploy the NodePort service for MLFlow
    type: boolean
    default: true
  serve_artifacts:
    description: |
      Enables serving of artifacts requests by routing these request to ./mlartifacts directory.
    type: boolean
    default: false
  artifacts_destination:
    description: |
      Base location URI of resolve artifact requests.
    type: string
    default: './mlartifacts'
