{
 "title": "MLflow metrics Dashboard",
 "time": { "from": "2023-07-06T18:24:35.162Z", "to": "2023-07-07T08:44:17.252Z" },
 "panels": [
  {
   "title": "MLflow up",
   "type": "stat",
   "description": "Displays if MLflow application is up (1) or down (0) for past 24 hours",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{juju_application=\"mlflow-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Experiments",
   "type": "timeseries",
   "description": "Number of MLflow experiments",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"num_experiments\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Registered Models",
   "type": "timeseries",
   "description": "Number of registered Models in MLflow over time ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"num_registered_models\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Runs",
   "type": "timeseries",
   "description": "Number of MLflow runs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"num_runs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration 5 minute windows by status code and method",
   "type": "timeseries",
   "description": "How long different types of requests by status code.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(mlflow_http_request_duration_seconds_sum[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Error requests per 30min window",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(mlflow_http_request_total{status=~\"40.\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}