#!/bin/bash
set -xeuo pipefail

echo "Using docker auth: $DOCKER_AUTH"

if [[ -z "${SKIP_SETUP:-}" && -z "${SKIP_SETUP_SNAPS:-}" ]]; then
    sudo snap remove microk8s --purge || true
    sudo snap install microk8s --channel 1.21/stable --classic
    echo '  [plugins."io.containerd.grpc.v1.cri".registry.configs]' >> /var/snap/microk8s/current/args/containerd-template.toml
    echo '    [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.io".auth]' >> /var/snap/microk8s/current/args/containerd-template.toml
    # Set DOCKER_AUTH to the "auth" part from ~/.docker/config for docker.io
    echo '      auth = "'$DOCKER_AUTH'"' >> /var/snap/microk8s/current/args/containerd-template.toml
    microk8s.stop; microk8s.start

    sudo snap remove juju --purge || true
    if [ -d ~/.local/share/juju ]; then
        mv ~/.local/share/juju ~/.local/share/juju-$(date +%s)
    fi
    sudo snap install juju --classic --channel=2.9/candidate
    sudo snap remove charmcraft --purge || true
    sudo snap install charmcraft
    #microk8s enable storage dns
fi

echo "Waiting for microk8s"
microk8s status --wait-ready

echo "Ensuring kubeconfig"
microk8s config > kubeconfig.microk8s
export KUBECONFIG=$(pwd)/kubeconfig.microk8s

if [ -z "${SKIP_SETUP:-}" ]; then
    #echo "Sleeping for 60 seconds to hopefully avoid falling down a crack"
    #sleep 60
    # https://juju.is/docs/olm/microk8s
    #until microk8s juju bootstrap microk8s micro; do
    #    echo "Waiting for juju bootstrap to succeed"
    #    sleep 1
    #done

    #juju deploy cs:bundle/kubeflow-267

    # Hrm, before we deploy kubeflow with juju, does this work? and avoid
    # https://github.com/canonical/bundle-kubeflow/issues/361
    microk8s enable kubeflow

    # Workaround https://github.com/canonical/bundle-kubeflow/issues/351#issuecomment-830044248
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    microk8s juju config oidc-gatekeeper public-url
    echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    #sleep 10
    #microk8s juju config oidc-gatekeeper public-url=http://10.64.140.43.nip.io/x
    #sleep 10
    #microk8s juju config oidc-gatekeeper public-url=http://10.64.140.43.nip.io/

fi

(cd mlflow && charmcraft build)
cp mlflow/mlflow.charm .
(cd worker && charmcraft build)
cp worker/worker.charm .

echo "Are you still ready, microk8s?"
microk8s status --wait-ready
echo "Sleeping for 120 seconds to hopefully avoid falling down another crack"
sleep 120

microk8s juju deploy ./bundle.yaml

microk8s juju relate mlflow:pod-defaults admission-webhook:pod-defaults
sleep 60
# workaround https://github.com/canonical/admission-webhook-operator/issues/4
kubectl get poddefaults -A -o yaml |sed 's/namespace: kubeflow/namespace: admin/' |kubectl apply -f - --namespace=admin

echo "Congrats. Try running:"
echo "    watch -c microk8s juju status --color"
echo "Also, follow step 6 onwards in: https://charmed-kubeflow.io/docs/install"
