# Copyright 2020 Luke Marsden
# See LICENSE file for licensing details.
#
options:
  default_artifact_root:
    description: |
      The name of the default bucket mlflow uses for artifacts, if not specified by the workflow
    type: string
    default: mlflow
  mlflow_port:
    description: |
      The port MLFlow will be listening on
    type: int
    default: 5000
  mlflow_nodeport:
    description: |
      The nodeport for MLFlow
    type: int
    default: 31380
  mlflow_scrape_interval:
    description: |
      How frequently to scrape targets from MLFlow.
    type: string
    default: None
  mlflow_scrape_timeout:
    description: |
      Per-scrape timeout when scraping MLFlow.
    type: string
    default: None
  minio_port:
    description: |
      The port Minio will be listening on
    type: int
    default: 9000
  minio_nodeport:
    description: |
      The nodeport for Minio
    type: int
    default: 30650
  kubeflow_port:
    description: |
      The port istio-ingressgateway will be listening on
    type: int
    default: 80
  kubeflow_nodeport:
    description: |
      The nodeport for Kubeflow (istio-ingressgateway)
    type: int
    default: 30600
