#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def master_relation_broken():
    """
    https://discourse.juju.is/t/charm-hooks/1040

    [name]-relation-broken indicates that the current relation is no longer valid, and that the charm’s software must
    be configured as though the relation had never existed. It will only be called after every necessary -departed hook
    has been run; if it’s being executed, you can be sure that no remote units are currently known locally.

    It is important to note that the -broken hook might run even if no other units have ever joined the relation.
    This is not a bug: even if no remote units have ever joined, the fact of the unit’s participation can be detected
    in other hooks via the relation-ids tool, and the -broken hook needs to execute to allow the charm to clean up any
    optimistically-generated configuration.

    And, again, it’s important to internalise the fact that there may be multiple runtime relations in play with the
    same name, and that they’re independent: one -broken hook does not mean that every such relation is broken.
    """
    log(" ========= hook: master-relation-broken  ========")

    # Remove the WORKERKEY.file
    os.remove("WORKERKEY.file")

if __name__ == "__main__":
    master_relation_broken()
