#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def master_relation_departed():
    """
    https://discourse.juju.is/t/charm-hooks/1040

    [name]-relation-departed is run once only, when the remote unit is known to be leaving the relation; it will only
    run once at least one -changed has been run, and after -departed has run, no further -changed hooks will be run.
    This should be used to remove all references to the remote unit, because there’s no guarantee that it’s still part
    of the system; it’s perfectly probable (although not guaranteed) that the system running that unit has already shut
    down.

    When a unit’s participation in a relation is known to be ending, the unit agent continues to uphold the ordering
    guarantees above; but within those constraints, it will run the fewest possible hooks to notify the charm of the
    departure of each remote unit.

    Once all necessary -departed hooks have been run for such a relation, the unit agent will run the final relation
    hook: [name]-relation-broken
    """

    log(" ========= hook: master-relation-departed  ========")


if __name__ == "__main__":
    master_relation_departed()
