#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def stop():
    """
    Lets not do anything here now but let the log know we passed through.
    """
    log("=========== hook: stop ===========")

if __name__ == "__main__":
    stop()
