#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charmhelpers.core import hookenv

def upgrade_charm():
    """
    Lets not do anything here now but let the log know we passed through.
    """
    hookenv.log(" ========= hook: upgrade-charm  ========")

if __name__ == "__main__":
    upgrade_charm()
