name: Main Documentation Checks

on:
  - push
  - pull_request

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yml@main
    with:
      working-directory: 'docs'