# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release

on:
  push:
    branches:
      - main
      - track/**

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release:
    name: Release charm
    needs: ci
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v31.0.0
    with:
      artifact-prefix: mlflow-server
      channel: latest/edge
      charmcraft-snap-channel: latest/edge
    secrets:
      charmhub-token: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
