name: TICS run self-hosted test (github-action)

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 2 * * 6" # Every Saturday 2:00 AM UTC

jobs:
  build:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]

    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install tox
          pip install pylint flake8

      - name: Run tox tests to create coverage.xml
        run: tox run -e unit

      - name: move results to necessary folder for TICS
        run: |
          mkdir cover
          mv coverage.xml cover/coverage.xml

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: mlflow-operator
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true